name: godot.yml
on:
  push:
    # Sequence of patterns matched against refs/tags
    #tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - 'ci'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Godot Engine Stuff
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: |
            /tmp/engine-godot
            /tmp/templates.tpz
          key: ${{ runner.os }}-godot
          
      - name: Install Godot Engine and Templates
        run: bash ./ci/install-godot.sh